major linting changes and fixes, code review
therealbenpai/BotClient pull request #3
Opened 2024-06-16 19:44 UTC by wrac4242

This is a PR just to try fixing a large amount of the issues in the code.
whats pulled up in this likely wont be the only things, but it will be a good start to it

Pulling this PR will require a major version bump due to breaking changes to the API

among the changes are:
moving eslint rules from pronouns page's repos into this repos to ensure standards
adding linting warnings for files containing too much stuff, to help incentivize moving to a modular and multi file approach
a few breaking changes to the API, e.g. removal of the "General" class

2024-06-26 02:09 UTC, therealbenpai requested changes
Note, I prefer to use 4 space indentation in my codebases. If possible, please format in this manor

2024-06-26 02:17 UTC, therealbenpai requested changes

2024-06-26 02:17 UTC, therealbenpai commented on src/index.ts
> +    handler: (client: Bot, interaction: djs.BaseInteraction<djs.CacheType>) => Promise<void>
Handler had declared a specific type of interaction that should remain

2024-06-26 02:17 UTC, therealbenpai commented on src/index.ts
> +    handler: (client: Bot, interaction: djs.BaseInteraction<djs.CacheType>) => Promise<void>
Handler had declared a specific type of interaction that should remain

2024-06-26 02:17 UTC, therealbenpai commented on src/index.ts
> +    handler: (client: Bot, interaction: djs.BaseInteraction<djs.CacheType>) => Promise<void>
Handler had declared a specific type of interaction that should remain

2024-06-26 02:17 UTC, therealbenpai commented on src/index.ts
> +    handler: (client: Bot, interaction: djs.BaseInteraction<djs.CacheType>) => Promise<void>
Handler had declared a specific type of interaction that should remain

2024-06-26 02:17 UTC, therealbenpai commented on eslint.config.js
These linting rules will be further altered to better fit the repository style

2024-06-26 02:17 UTC, therealbenpai commented on src/index.ts
> +  noClueWhatThisIsUsedToBeGev = (name: string) =>
```suggestion
  generateEvent = (name: string) =>
```

2024-06-26 02:19 UTC, therealbenpai commented
Other than these few changes, there isn't much that I can see than needs to be changed

2024-06-26 11:02 UTC, wrac4242 commented
main thing is also typedoc needs updating
as its very very very clear its blindly copied from another project without edits

2024-06-26 11:09 UTC, wrac4242 commented
though i just fixed that now

2024-06-26 11:23 UTC, wrac4242 commented
I am having some major typing issues with how you are handling the interactions type. I am currently just bodging it together.

2024-06-26 11:24 UTC, wrac4242 commented
i will need to split a lot of the things into their own files as this is too messy

2025-01-01 18:55 UTC, wrac4242 commented
Been too long since i touched this. its a massive shame it got missed

2025-01-01 18:55 UTC, closed without merging

2025-01-01 18:55 UTC, wrac4242 commented
Will reoen a new PR soon with changes as a lot of the same issues are present